%%{init: {'theme': 'base', 'themeVariables': { 'participantBkg': '#FFCCCC', 'participantBorder': '#333'}}}%%
sequenceDiagram
    participant Usuario
    participant Servidor
    Usuario->>Servidor: Solicitar datos
    Servidor-->>Usuario: Enviar datos
    Usuario->>Servidor: Confirmar recepción
    Servidor-->>Usuario: Confirmación recibida
